export enum UserRole {
  STUDENT = 'STUDENT',
  COMPANY = 'COMPANY',
  ADMIN = 'ADMIN',
}

export enum NotificationType {
  PROJECT_APPROVED = 'PROJECT_APPROVED',
  PROJECT_REJECTED = 'PROJECT_REJECTED',
  SKILL_VERIFIED = 'SKILL_VERIFIED',
  BADGE_EARNED = 'BADGE_EARNED',
  APPLICATION_RECEIVED = 'APPLICATION_RECEIVED',
  PAYMENT_SUCCESS = 'PAYMENT_SUCCESS',
  SYSTEM_ANNOUNCEMENT = 'SYSTEM_ANNOUNCEMENT',
}

export enum SkillLevel {
  BEGINNER = 'BEGINNER',
  INTERMEDIATE = 'INTERMEDIATE',
  ADVANCED = 'ADVANCED',
  EXPERT = 'EXPERT',
}

export enum BadgeType {
  SKILL = 'SKILL',
  PROJECT = 'PROJECT',
  ACHIEVEMENT = 'ACHIEVEMENT',
  COMMUNITY = 'COMMUNITY',
}
